### ISSUE TITLE
This is not a minimal FTP server.  It is RSA extended

### ISSUE THREAD

**Issue by hilbix** [CalciferZh/TinyFtp#1]
I was looking for a minimal RFC 959 FTP implementation.

https://github.com/CalciferZh/TinyFTP/blob/bb70b54a5c71a8e1896da02f56591db0e6bbbd5c/README.md#L2

however

https://github.com/CalciferZh/TinyFTP/blob/bb70b54a5c71a8e1896da02f56591db0e6bbbd5c/README.md#L6

Such an RSA **extension** clearly defeats the claim to be **minimal**.

**Comment by CalciferZh** [comment]
You're right.
